version: '2'
services:

  database_test:
    image:  "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    container_name: sequelize_pg_stream
    # docker exec -it sequelize_pg_stream psql psql -d test -U test --password test